#!/usr/bin/env python3
"""ECS 上用 Playwright 真实登录抖音，持久化登录态并导出 Netscape cookie。

设计：分两阶段，避免 SSH 交互式输入不稳定。
  --stage request : 打开登录页、切手机号、填号、点"获取验证码"。等待短信。
  --stage submit  : 复用同一 profile 打开登录页、填验证码、提交，登录后导出 cookie。

前置（ECS 上一次）：
  cd /opt/vdl-worker
  .venv/bin/pip install playwright
  .venv/bin/python -m playwright install chromium

用法：
  .venv/bin/python douyin_ecs_login.py --phone 138xxxx --stage request
  .venv/bin/python douyin_ecs_login.py --stage submit --code 123456
  .venv/bin/python douyin_ecs_login.py --verify https://v.douyin.com/xxxx/   # 可选：用导出 cookie 验解析

反爬提示：Douyin 可能对无头浏览器弹滑块验证。脚本会检测常见滑块并明确报错，
此时请回退到 VNC 扫码方案（VDL_phaseB_vnc.sh）。
"""
import argparse
import os
import sys
import time
from pathlib import Path

PROFILE = "/opt/vdl-worker/chrome_profile"
COOKIE_OUT = "/opt/vdl-worker/cookies/douyin.com.txt"
LOGIN_URL = "https://www.douyin.com/login"


def _need_playwright():
    try:
        from playwright.sync_api import sync_playwright  # noqa: F401
        return True
    except ImportError:
        print("❌ 未安装 playwright。请先执行：")
        print("   cd /opt/vdl-worker && .venv/bin/pip install playwright && .venv/bin/python -m playwright install chromium")
        sys.exit(1)


def launch():
    from playwright.sync_api import sync_playwright

    Path(PROFILE).mkdir(parents=True, exist_ok=True)
    pw = sync_playwright().start()
    browser = pw.chromium.launch(
        headless=True,
        args=[
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "--disable-blink-features=AutomationControlled",
        ],
    )
    context = browser.new_context(
        user_data_dir=PROFILE,
        user_agent=(
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
        ),
        viewport={"width": 1280, "height": 800},
        locale="zh-CN",
    )
    # 抹掉 webdriver 标记，降低被识别为自动化的概率
    context.add_init_script(
        "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
    )
    return pw, browser, context


def _detect_slider(page):
    """检测常见滑块验证元素，返回 True 表示命中。"""
    for sel in [
        "text=滑动验证", "text=请滑动", "text=安全验证",
        "[class*=slider]", "[class*=captcha]", "[class*=secsdk]",
    ]:
        try:
            if page.locator(sel).first.is_visible(timeout=1500):
                return True
        except Exception:
            pass
    return False


def export_netscape(context):
    cookies = context.cookies()
    lines = ["# Netscape HTTP Cookie File", "# Generated by douyin_ecs_login.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = int(c.get("expires", 0)) if c.get("expires") else 0
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append("\t".join([domain, include_sub, path, secure, str(expiry), name, value]))
    Path(COOKIE_OUT).parent.mkdir(parents=True, exist_ok=True)
    with open(COOKIE_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(cookies)


def stage_request(phone):
    pw, browser, context = launch()
    page = context.new_page()
    try:
        page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=30000)
        time.sleep(2)
        if _detect_slider(page):
            print("❌ 登录页出现滑块验证，Playwright 无法自动处理。请改用 VNC 扫码方案。")
            return
        # 切到"手机号登录"：优先点含"手机号"文字的标签/按钮
        for sel in ["text=手机号登录", "text=手机号", "text=密码登录"]:
            try:
                loc = page.get_by_text(sel, exact=False).first
                if loc.is_visible(timeout=2000):
                    loc.click()
                    break
            except Exception:
                pass
        time.sleep(1)
        # 填手机号：找 placeholder 含"手机号"的输入框
        phone_filled = False
        for sel in ["input[placeholder*=手机号]", "input[type=tel]", "input[name*=phone]"]:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=2000):
                    el.fill(phone)
                    phone_filled = True
                    break
            except Exception:
                pass
        if not phone_filled:
            print("⚠️ 未找到手机号输入框，可能页面结构变化。当前页面文本快照：")
            print(page.inner_text("body")[:500])
            return
        # 点"获取验证码 / 发送验证码"
        sent = False
        for sel in ["text=获取验证码", "text=发送验证码", "text=获取短信验证码"]:
            try:
                loc = page.get_by_text(sel, exact=False).first
                if loc.is_visible(timeout=2000):
                    loc.click()
                    sent = True
                    break
            except Exception:
                pass
        time.sleep(2)
        if _detect_slider(page):
            print("❌ 点击获取验证码后弹出滑块验证，Playwright 无法自动处理。请改用 VNC 扫码方案。")
            return
        if not sent:
            print("⚠️ 未找到'获取验证码'按钮。页面文本快照：")
            print(page.inner_text("body")[:500])
            return
        print("✅ 验证码已发送，请查看手机短信。")
        print("   收到后执行：")
        print(f"   .venv/bin/python {os.path.basename(__file__)} --stage submit --code <你的验证码>")
    finally:
        browser.close()
        pw.stop()


def stage_submit(code):
    pw, browser, context = launch()
    page = context.new_page()
    try:
        page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=30000)
        time.sleep(2)
        if _detect_slider(page):
            print("❌ 提交前出现滑块验证。请改用 VNC 扫码方案。")
            return
        # 填验证码：找 placeholder 含"验证码"的输入框
        code_filled = False
        for sel in ["input[placeholder*=验证码]", "input[name*=code]", "input[maxlength='6']"]:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=2000):
                    el.fill(code)
                    code_filled = True
                    break
            except Exception:
                pass
        if not code_filled:
            print("⚠️ 未找到验证码输入框。页面文本快照：")
            print(page.inner_text("body")[:500])
            return
        # 点登录
        for sel in ["text=登录", "button:has-text('登录')"]:
            try:
                loc = page.locator(sel).first
                if loc.is_visible(timeout=2000):
                    loc.click()
                    break
            except Exception:
                pass
        # 等待登录成功（URL 跳回 douyin.com 主页 或 出现个人中心）
        try:
            page.wait_for_url("**/douyin.com/**", timeout=15000)
        except Exception:
            pass
        time.sleep(3)
        if _detect_slider(page):
            print("❌ 登录后触发滑块验证。请改用 VNC 扫码方案。")
            return
        cookies = context.cookies()
        has_session = any(
            c.get("name") in ("sessionid", "sessionid_ss", "sid_tt", "uid_tt")
            for c in cookies
        )
        if not has_session:
            print("⚠️ 未检测到登录态 Cookie（sessionid 等）。可能登录未成功。页面文本：")
            print(page.inner_text("body")[:500])
            return
        n = export_netscape(context)
        print(f"✅ 登录成功，已导出 {n} 条 Cookie 到 {COOKIE_OUT}")
        print("   下一步可在 ECS 用 yt-dlp 验证：")
        print(f"   .venv/bin/python douyin_ecs_login.py --verify <抖音链接>")
    finally:
        browser.close()
        pw.stop()


def stage_verify(url):
    import json
    import yt_dlp

    if not os.path.exists(COOKIE_OUT):
        print(f"❌ 未找到 cookie 文件 {COOKIE_OUT}，请先完成登录。")
        sys.exit(1)
    opts = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "cookies": COOKIE_OUT,
        "proxy": "",
    }
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
            print("✅ 解析成功：")
            print(json.dumps({
                "title": info.get("title"),
                "duration": info.get("duration"),
                "uploader": info.get("uploader"),
            }, ensure_ascii=False, indent=2))
    except Exception as e:
        print("❌ 解析失败：", str(e))


def main():
    _need_playwright()
    ap = argparse.ArgumentParser()
    ap.add_argument("--phone", help="手机号（request 阶段必填）")
    ap.add_argument("--code", help="短信验证码（submit 阶段必填）")
    ap.add_argument("--stage", choices=["request", "submit", "verify"], required=True)
    ap.add_argument("--verify-url", dest="verify_url", help="verify 阶段的抖音链接")
    args = ap.parse_args()

    if args.stage == "request":
        if not args.phone:
            print("❌ request 阶段需要 --phone 手机号")
            sys.exit(1)
        stage_request(args.phone)
    elif args.stage == "submit":
        if not args.code:
            print("❌ submit 阶段需要 --code 验证码")
            sys.exit(1)
        stage_submit(args.code)
    elif args.stage == "verify":
        if not args.verify_url:
            print("❌ verify 阶段需要 --verify-url 抖音链接")
            sys.exit(1)
        stage_verify(args.verify_url)


if __name__ == "__main__":
    main()
