#!/usr/bin/env python3
"""复用已登录的 Chrome profile，读取 youku cookie 并导出 + 贡献。

前提：用户已用 youku_login.py 扫码登录优酷，Chrome 窗口保持打开（profile 锁定）。
本脚本用同一个 user_data_dir 启动新 context，读取已落地的 cookie。

用法：
  .build_venv/bin/python youku_read_cookie.py            # 读 + 导出 + UPS 校验
  .build_venv/bin/python youku_read_cookie.py --contribute   # 额外贡献到共享池
"""
import argparse
import json
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROFILE = str(HERE / "chrome_profile_youku")
COOKIE_DIR = HERE / "cookies"
NETSCAPE_OUT = COOKIE_DIR / "youku.com.txt"
HEADER_OUT = COOKIE_DIR / "youku.com.header"
TEST_VID = "XMjQ0ODk0Njg0"
CONTRIBUTE_URL = "https://hanyuxz.top/api/cookie/contribute"
CONTRIBUTE_UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                 "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--contribute", action="store_true")
    args = ap.parse_args()

    from playwright.sync_api import sync_playwright
    pw = sync_playwright().start()
    context = pw.chromium.launch_persistent_context(
        user_data_dir=PROFILE,
        headless=True,
        channel="chrome",
        args=["--no-sandbox", "--disable-dev-shm-usage", "--disable-blink-features=AutomationControlled"],
        user_agent=("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                     "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"),
        locale="zh-CN",
    )
    try:
        # 先导航到 youku 让 cookie 域名上下文生效
        page = context.new_page()
        page.goto("https://www.youku.com", wait_until="domcontentloaded", timeout=30000)
        import time
        time.sleep(2)
        cookies = context.cookies()
        yk = [c for c in cookies if "youku.com" in c.get("domain", "")]
        print(f"读到 youku 相关 cookie 数: {len(yk)}")
        has_uck = any(c.get("name") == "P__yk__uck" for c in yk)
        has_session = any(c.get("name") == "SESSIONID" for c in yk)
        print(f"  含 P__yk__uck: {'✅ YES' if has_uck else '❌ NO'}")
        print(f"  含 SESSIONID:  {'✅ YES' if has_session else '⚠️ NO'}")

        if not yk:
            print("❌ 未读到 youku cookie。可能 Chrome 窗口已关或 profile 未锁定登录态。")
            sys.exit(1)

        # 导出
        COOKIE_DIR.mkdir(parents=True, exist_ok=True)
        lines = ["# Netscape HTTP Cookie File", "# Generated by youku_read_cookie.py", ""]
        for c in yk:
            domain = c.get("domain", "")
            include_sub = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure") else "FALSE"
            expiry = int(c.get("expires", 0)) if c.get("expires") else 0
            lines.append("\t".join([domain, include_sub, path, secure, str(expiry), c.get("name", ""), c.get("value", "")]))
        NETSCAPE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

        header = "; ".join(f"{c['name']}={c['value']}" for c in yk)
        HEADER_OUT.write_text(header, encoding="utf-8")
        print(f"✅ 已导出 Netscape: {NETSCAPE_OUT}")
        print(f"✅ 已导出 Header  : {HEADER_OUT}")

        # UPS 校验
        cna = next((c["value"] for c in yk if c["name"] == "cna"), "")
        url = f"https://ups.youku.com/ups/get.json?vid={TEST_VID}&ccode=0564&utid={cna}"
        req = urllib.request.Request(url, headers={
            "User-Agent": CONTRIBUTE_UA,
            "Referer": "https://v.youku.com/",
            "Cookie": header,
        })
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                data = json.loads(r.read().decode("utf-8", "ignore"))
            user = data.get("data", {}).get("user", {})
            login = user.get("login")
            print(f"UPS user.login: {login!r}")
            if login:
                print("✅ UPS 校验通过，-3007 应可消（若该账号有此片权限）。")
            else:
                print("⚠️ UPS user.login 为空，登录态可能未真正落地或账号非会员。")
        except Exception as e:
            print(f"⚠️ UPS 校验失败: {str(e)[:160]}")

        # 贡献
        if args.contribute:
            if "P__yk__uck" not in header:
                print("❌ 贡献中止：header 不含 P__yk__uck，贡献了也消不掉 -3007。")
                sys.exit(1)
            payload = json.dumps({"host": "youku.com", "cookie": header}).encode("utf-8")
            creq = urllib.request.Request(CONTRIBUTE_URL, data=payload, method="POST", headers={
                "User-Agent": CONTRIBUTE_UA,
                "Content-Type": "application/json",
                "Origin": "https://hanyuxz.top",
                "Referer": "https://hanyuxz.top/",
            })
            try:
                with urllib.request.urlopen(creq, timeout=20) as r:
                    body = r.read().decode("utf-8", "ignore")
                print(f"✅ 已贡献到共享池：{body[:200]}")
            except Exception as e:
                print(f"⚠️ 贡献失败: {str(e)[:160]}")
    finally:
        context.close()
        pw.stop()


if __name__ == "__main__":
    main()
