#!/usr/bin/env python3
"""
优酷自动登录：弹窗 -> 扫码 -> 检测登录态 -> 导出 cookie -> 贡献共享池。
扫码那一步需用户用手机确认，其余全自动。

用法：
  .build_venv/bin/python youku_auto_login.py            # 登录+导出+UPS校验
  .build_venv/bin/python youku_auto_login.py --contribute   # 额外贡献共享池
"""
import argparse
import json
import sys
import time
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROFILE = str(HERE / "chrome_profile_youku")
COOKIE_DIR = HERE / "cookies"
NETSCAPE_OUT = COOKIE_DIR / "youku.com.txt"
HEADER_OUT = COOKIE_DIR / "youku.com.header"
QR_IMG = COOKIE_DIR / "youku_qr.png"
TEST_VID = "XMjQ0ODk0Njg0"
LOGIN_MARKERS = ("P__yk__uck", "SESSIONID", "last_ud_youku", "_uab_collina", "ykus_utid", "P_sck")
CONTRIBUTE_URL = "https://hanyuxz.top/api/cookie/contribute"
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")


def launch():
    from playwright.sync_api import sync_playwright
    Path(PROFILE).mkdir(parents=True, exist_ok=True)
    pw = sync_playwright().start()
    context = pw.chromium.launch_persistent_context(
        user_data_dir=PROFILE,
        headless=False,
        channel="chrome",
        args=["--no-sandbox", "--disable-dev-shm-usage", "--disable-blink-features=AutomationControlled"],
        user_agent=UA, viewport={"width": 1280, "height": 800}, locale="zh-CN",
    )
    context.add_init_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
    return pw, context.browser, context


def export_cookies(context):
    cookies = context.cookies()
    yk = [c for c in cookies if "youku.com" in c.get("domain", "")]
    COOKIE_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by youku_auto_login.py", ""]
    for c in yk:
        domain = c.get("domain", "")
        inc = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        sec = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expires", 0)) if c.get("expires") else 0
        lines.append("\t".join([domain, inc, path, sec, str(exp), c.get("name", ""), c.get("value", "")]))
    NETSCAPE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    header = "; ".join(f"{c['name']}={c['value']}" for c in yk)
    HEADER_OUT.write_text(header, encoding="utf-8")
    return yk, header


def ups_verify(header):
    cna = ""
    for part in header.split("; "):
        if part.startswith("cna="):
            cna = part[4:]
            break
    url = f"https://ups.youku.com/ups/get.json?vid={TEST_VID}&ccode=0564&utid={cna}"
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Referer": "https://v.youku.com/", "Cookie": header})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            d = json.loads(r.read().decode("utf-8", "ignore"))
        login = d.get("data", {}).get("user", {}).get("login")
        print(f"UPS user.login: {login!r}")
        return login
    except Exception as e:
        print(f"⚠️ UPS 校验失败: {str(e)[:160]}")
        return None


def contribute(header):
    if "P__yk__uck" not in header and "last_ud_youku" not in header:
        print("⚠️ 贡献中止：未检测到明确登录票据，贡献可能无效。")
        return
    payload = json.dumps({"host": "youku.com", "cookie": header}).encode("utf-8")
    req = urllib.request.Request(CONTRIBUTE_URL, data=payload, method="POST", headers={
        "User-Agent": UA, "Content-Type": "application/json",
        "Origin": "https://hanyuxz.top", "Referer": "https://hanyuxz.top/",
    })
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            print(f"✅ 已贡献到共享池：{r.read().decode('utf-8','ignore')[:200]}")
    except Exception as e:
        print(f"⚠️ 贡献失败: {str(e)[:160]}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--contribute", action="store_true")
    args = ap.parse_args()

    pw, browser, context = launch()
    page = context.new_page()
    try:
        print("🌐 打开优酷首页 ...")
        page.goto("https://www.youku.com", wait_until="domcontentloaded", timeout=30000)
        time.sleep(2)

        # 点登录按钮
        clicked = False
        for loc in [page.get_by_text("登录", exact=False).first]:
            try:
                if loc.is_visible(timeout=3000):
                    loc.click()
                    clicked = True
                    break
            except Exception:
                pass
        print("🔘 已点击登录" if clicked else "ℹ️ 未点到登录按钮（可能已是登录态或页面结构不同）")
        time.sleep(3)

        # 切到扫码
        for loc in [page.get_by_text("扫码", exact=False).first, page.get_by_text("二维码", exact=False).first]:
            try:
                if loc.is_visible(timeout=2000):
                    loc.click()
                    break
            except Exception:
                pass
        time.sleep(2)

        # 截图二维码
        page.screenshot(path=str(QR_IMG))
        print(f"📱 二维码已截图：{QR_IMG}")

        # 轮询登录态
        print("⏳ 等待扫码确认（最多 150s）...")
        deadline = time.time() + 150
        logged = False
        last_btn = True
        while time.time() < deadline:
            try:
                still = page.get_by_text("登录", exact=False).first.is_visible(timeout=600)
            except Exception:
                still = False
            cookies = context.cookies()
            yk = [c for c in cookies if "youku.com" in c.get("domain", "")]
            if not still and yk:
                logged = True
                print("   ✅ 登录按钮消失 + 有 youku cookie => 已登录")
                break
            if any(c.get("name") in LOGIN_MARKERS for c in yk):
                logged = True
                print(f"   ✅ 登录票据: {[c['name'] for c in yk if c['name'] in LOGIN_MARKERS]}")
                break
            last_btn = still
            time.sleep(1)

        if not logged:
            print("❌ 150s 未检测到登录态。请确认手机已扫码并点「确认登录」。")
            return

        # 触发票据落地
        print("🌐 访问播放页触发票据落地 ...")
        try:
            page.goto(f"https://v.youku.com/v_show/id_{TEST_VID}.html", wait_until="domcontentloaded", timeout=30000)
            time.sleep(4)
        except Exception:
            pass
        time.sleep(2)

        yk, header = export_cookies(context)
        print(f"✅ 导出 {len(yk)} 条 youku cookie")
        login = ups_verify(header)
        if login:
            print("✅ UPS 校验通过")
        else:
            print("⚠️ UPS 未认登录态（可能账号非会员或票据不全）")
        if args.contribute:
            contribute(header)
    finally:
        browser.close()
        pw.stop()


if __name__ == "__main__":
    main()
