#!/usr/bin/env python3
"""用账号密码自动登录优酷，落到 chrome_profile_youku（供浏览器引擎零门槛解析用）。

与 youku_login.py（扫码）互补：本脚本用手机号+密码直接登录，无需手机扫码。

用法：
  .build_venv/bin/python youku_login_pwd.py --username 15638319956 --password 'xxxx'
"""
import argparse
import os
import sys
import time
import json
import urllib.request
import urllib.error
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROFILE = str(HERE / "chrome_profile_youku")
COOKIE_DIR = HERE / "cookies"
NETSCAPE_OUT = COOKIE_DIR / "youku.com.txt"
HEADER_OUT = COOKIE_DIR / "youku.com.header"
TEST_VID = "XMjQ0ODk0NTAw"


def launch(headless):
    from playwright.sync_api import sync_playwright
    Path(PROFILE).mkdir(parents=True, exist_ok=True)
    pw = sync_playwright().start()
    context = pw.chromium.launch_persistent_context(
        user_data_dir=PROFILE,
        headless=headless,
        channel="chrome",
        args=[
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "--disable-blink-features=AutomationControlled",
        ],
        user_agent=(
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
        ),
        viewport={"width": 1280, "height": 800},
        locale="zh-CN",
    )
    context.add_init_script(
        "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
    )
    return pw, context.browser, context


def _export(cookies):
    COOKIE_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by youku_login_pwd.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = int(c.get("expires", 0)) if c.get("expires") else 0
        lines.append("\t".join([domain, include_sub, path, secure, str(expiry),
                                c.get("name", ""), c.get("value", "")]))
    NETSCAPE_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    yk = [c for c in cookies if "youku.com" in c.get("domain", "")]
    header = "; ".join(f"{c['name']}={c['value']}" for c in yk)
    HEADER_OUT.write_text(header, encoding="utf-8")
    return len(cookies)


def login(username, password, headless):
    pw, browser, context = launch(headless)
    page = context.new_page()
    try:
        print("🌐 打开优酷登录页 ...")
        page.goto("https://www.youku.com", wait_until="domcontentloaded", timeout=30000)
        time.sleep(2)
        # 触发登录弹层
        for kw in ["登录", "登录/注册", "账号登录"]:
            try:
                loc = page.get_by_text(kw, exact=False).first
                if loc.is_visible(timeout=1500):
                    loc.click()
                    print(f"   点击「{kw}」")
                    break
            except Exception:
                pass
        time.sleep(2)
        time.sleep(2)

        # 切到「密码登录」标签
        switched = False
        for kw in ["密码登录", "账号密码登录", "短信登录", "密码"]:
            try:
                loc = page.get_by_text(kw, exact=False).first
                if loc.is_visible(timeout=1500):
                    loc.click()
                    switched = True
                    print(f"   切到「{kw}」")
                    break
            except Exception:
                pass
        time.sleep(1)

        # 填账号密码。优酷登录页输入框用 name / placeholder 定位
        filled = False
        # 账号框
        for sel in ["input[name=loginId]", "input[placeholder*=账号]", "input[placeholder*=手机号]",
                    "input[name=username]", "#username"]:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=1500):
                    el.fill(username)
                    print("   已填账号")
                    filled = True
                    break
            except Exception:
                pass
        # 密码框
        for sel in ["input[name=password]", "input[type=password]", "input[placeholder*=密码]",
                    "#password"]:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=1500):
                    el.fill(password)
                    print("   已填密码")
                    break
            except Exception:
                pass
        if not filled:
            print("⚠️ 未能定位账号输入框，可能页面结构变化。尝试截图调试。")
            try:
                page.screenshot(path=str(COOKIE_DIR / "youku_pwd_page.png"))
                print(f"   截图：{COOKIE_DIR / 'youku_pwd_page.png'}")
            except Exception:
                pass

        # 点登录按钮
        clicked = False
        for sel in ["button:has-text('登录')", "input[type=submit]", "#submitBtn",
                    "button[type=submit]"]:
            try:
                el = page.locator(sel).first
                if el.is_visible(timeout=1500):
                    el.click()
                    clicked = True
                    print("   已点登录")
                    break
            except Exception:
                pass
        if not clicked:
            print("⚠️ 未找到登录按钮")

        # 轮询登录态
        LOGIN_MARKERS = ("P__yk__uck", "SESSIONID", "last_ud_youku", "_uab_collina",
                         "ykus_utid", "cna")
        print("⏳ 等待登录（最多 120s）...")
        deadline = time.time() + 120
        logged = False
        while time.time() < deadline:
            try:
                still_login = page.get_by_text("登录", exact=False).first.is_visible(timeout=600)
            except Exception:
                still_login = False
            cookies = context.cookies()
            yk = [c for c in cookies if "youku.com" in c.get("domain", "")]
            has_marker = any(c.get("name") in LOGIN_MARKERS for c in yk)
            if not still_login and yk:
                logged = True
                print("   ✅ 登录按钮消失且存在 youku cookie")
                break
            if has_marker and any(c.get("name") == "cna" for c in yk):
                # cna 是登录后一定有的，结合按钮消失更稳
                pass
            if "P__yk__uck" in [c.get("name") for c in yk]:
                logged = True
                print("   ✅ 检测到 P__yk__uck 登录票据")
                break
            time.sleep(1)

        if not logged:
            # 截图看卡在哪
            try:
                page.screenshot(path=str(COOKIE_DIR / "youku_pwd_page.png"))
                print(f"   登录超时，截图：{COOKIE_DIR / 'youku_pwd_page.png'}")
            except Exception:
                pass
            print("❌ 120s 内未登录成功。可能：验证码、滑块、账号密码错、或风控。")
            return False

        # 触发票据落地
        try:
            page.goto(f"https://v.youku.com/v_show/id_{TEST_VID}.html",
                      wait_until="domcontentloaded", timeout=30000)
            time.sleep(4)
        except Exception:
            pass
        cookies = context.cookies()
        n = _export(cookies)
        print(f"✅ 登录成功，导出 {n} 条 cookie")
        _ups_verify()
        return True
    finally:
        browser.close()
        pw.stop()


def _ups_verify():
    if not HEADER_OUT.exists():
        return
    header = HEADER_OUT.read_text(encoding="utf-8").strip()
    if not header:
        return
    try:
        cna = ""
        for kv in header.split(";"):
            kv = kv.strip()
            if kv.startswith("cna="):
                cna = kv[4:]
                break
        url = f"https://ups.youku.com/ups/get.json?vid={TEST_VID}&ccode=0564&utid={cna}"
        req = urllib.request.Request(url, headers={
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
            "Referer": "https://v.youku.com/",
            "Cookie": header,
        })
        with urllib.request.urlopen(req, timeout=20) as r:
            data = json.loads(r.read().decode("utf-8", "ignore"))
        user = data.get("data", {}).get("user", {})
        login = user.get("login")
        print(f"✅ UPS 校验：user.login={login!r}" if login else "⚠️ UPS user.login 仍为空")
    except Exception as e:
        print(f"⚠️ UPS 校验失败：{str(e)[:160]}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--username", required=True)
    ap.add_argument("--password", required=True)
    ap.add_argument("--headless", action="store_true")
    args = ap.parse_args()
    ok = login(args.username, args.password, args.headless)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
